name: al_khazna
description: A simple app for tracking monthly income and expenses.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  pdf: ^3.10.7
  printing: ^5.11.1
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  
  # Google Sign-In & Drive (WhatsApp-style backup)
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  
  # Encryption
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.2
  
  # Local Database
  sqflite: ^2.3.3
  
  # Background Tasks
  workmanager: ^0.9.0
  
  # Utilities
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.1
  
  # UI Components
  percent_indicator: ^4.2.3
  flutter_local_notifications: ^17.1.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
          # You can add different weights if you have the font files, e.g.:
        # - asset: assets/fonts/NotoSansArabic-Bold.ttf
        #   weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#2196f3"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48

