name: al_khazna
description: A simple app for tracking monthly income and expenses.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  pdf: ^3.10.7 # Already present
  printing: ^5.11.1 # Already present
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # logging: ^1.3.0 # This was in the user's pubspec, keeping it
  # path_provider is used by printing or if saving file locally, ensure it's here if not transitive
  path_provider: ^2.0.0 # Adding for completeness, printing might need it directly or transitively
  encrypt: ^5.0.3
  file_picker: ^8.0.7
  permission_handler: ^12.0.1
  pointycastle: ^3.9.1
  archive: ^4.0.7
  # Firebase dependencies for cloud backup
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.7.7
  google_sign_in: ^6.2.1
  # google_api_availability removed (not used)
  # Google Services dependency
  firebase_messaging: ^14.7.10
  # Performance and background processing
  flutter_local_notifications: ^18.0.1
  crypto: ^3.0.5
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
          # You can add different weights if you have the font files, e.g.:
        # - asset: assets/fonts/NotoSansArabic-Bold.ttf
        #   weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#2196f3"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48

